version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    restart: unless-stopped
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./backup:/usr/share/elasticsearch/backup
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9201:9200"
  cortex:
    image: cortex:3.1.2-SNAPSHOT
    restart: unless-stopped
    command: ["sh", "-c", "rm -f /opt/cortex/RUNNING_PID && bin/cortex -Dconfig.file=conf/application.conf -Dsearch.uri=http://elasticsearch:9200 -Dplay.http.secret.key=changeme-to-a-very-secure-random-string-for-cortex-production-mode -Dhttp.port=9000 -Danalyzer.urls.0=/opt/cortex/analyzers/analyzers -Dresponder.urls.0=/opt/cortex/analyzers/responders"]
    environment:
      - job_directory=${job_directory}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${job_directory}:${job_directory}
      - ../../analyzers:/opt/cortex/analyzers
      - ./cortex-assets-new.jar:/opt/cortex/lib/org.thehive-project.cortex-4.0.1-1-assets.jar
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9000:9000"

volumes:
  es_data: